# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2024-2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from alembic import op
import sqlalchemy as sa


revision = "0be827860b2d"
down_revision = "2816939acb1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("extraction_events_exercise_id_fkey", "extraction_events", type_="foreignkey")
    op.create_foreign_key(None, "extraction_events", "exercises", ["exercise_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("extraction_events_exercise_id_fkey", "extraction_events", type_="foreignkey")
    op.create_foreign_key("extraction_events_exercise_id_fkey", "extraction_events", "exercises", ["exercise_id"], ["id"])
    # ### end Alembic commands ###
