# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2024-2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm


from gabby.exercises import Exercise


revision = "33389ce52383"
down_revision = "e27fe2c311ad"
branch_labels = None
depends_on = None


def fix_ellipsis(obj):
    # Fragile, ad-hoc, but works well for this replacement because it does not interfere with the JSON syntax.
    return json.loads(json.dumps(obj).replace("\\u2026", "..."))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "instructions_text")
    op.drop_column("exercises", "clue_text")
    op.drop_column("exercises", "example_text")
    op.drop_column("exercises", "wording_text")
    # ### end Alembic commands ###

    # Data migration
    with orm.Session(op.get_bind()) as session:
        for exercise in session.query(Exercise).all():
            for field in ["_instructions", "_wording", "_example", "_clue", "_text_reference"]:
                value = fix_ellipsis(getattr(exercise, field))
                for insert_operation in value:
                    assert "selectable" not in insert_operation["attributes"], (
                        "Unhandled old 'selectable' attribute",
                        exercise.id,
                    )  # None in real-life DB => don't need to migrate
                setattr(exercise, field, value)

            exercise._rectangles = fix_ellipsis(exercise._rectangles)

            adaptation = fix_ellipsis(exercise._adaptation)
            for effect in adaptation["settings"]["effects"]:
                if effect["kind"] == "itemized":
                    if effect["items"]["kind"] == "words":
                        effect["items"] = {"kind": "tokens", "words": True, "punctuation": effect["items"]["punctuation"]}

            exercise._adaptation = adaptation
        session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercises", sa.Column("wording_text", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("exercises", sa.Column("example_text", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("exercises", sa.Column("clue_text", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("exercises", sa.Column("instructions_text", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
