# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2024-2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from alembic import op
import sqlalchemy as sa


revision = "e27fe2c311ad"
down_revision = "7ef48883e57b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "instructions", new_column_name="instructions_text", nullable=True)
    op.alter_column("exercises", "wording", new_column_name="wording_text", nullable=True)
    op.alter_column("exercises", "example", new_column_name="example_text", nullable=True)
    op.alter_column("exercises", "clue", new_column_name="clue_text", nullable=True)
    op.add_column("exercises", sa.Column("instructions", sa.JSON(), server_default='[{"insert": "\\n", "attributes": {}}]', nullable=False))
    op.add_column("exercises", sa.Column("wording", sa.JSON(), server_default='[{"insert": "\\n", "attributes": {}}]', nullable=False))
    op.add_column("exercises", sa.Column("example", sa.JSON(), server_default='[{"insert": "\\n", "attributes": {}}]', nullable=False))
    op.add_column("exercises", sa.Column("clue", sa.JSON(), server_default='[{"insert": "\\n", "attributes": {}}]', nullable=False))
    op.add_column("exercises", sa.Column("text_reference", sa.JSON(), server_default='[{"insert": "\\n", "attributes": {}}]', nullable=False))
    op.alter_column("exercises", "wording_paragraphs_per_pagelet", existing_type=sa.INTEGER(), nullable=True, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "wording_paragraphs_per_pagelet", existing_type=sa.INTEGER(), nullable=False, server_default=sa.text("3"))
    op.drop_column("exercises", "clue")
    op.drop_column("exercises", "example")
    op.drop_column("exercises", "wording")
    op.drop_column("exercises", "instructions")
    op.alter_column("exercises", "instructions_text", new_column_name="instructions")
    op.alter_column("exercises", "wording_text", new_column_name="wording")
    op.alter_column("exercises", "example_text", new_column_name="example")
    op.alter_column("exercises", "clue_text", new_column_name="clue")
    op.drop_column("exercises", "text_reference")
    # ### end Alembic commands ###
